version: '3.4'

services:
  reverse_tcp:
    image: reverse_shell
    expose:
      - 4444
    ports:
      - 4444:4444
    networks:
      the_internet:
        ipv4_address: 10.5.0.5

  curl_attacker:
    image: curler
    networks:
      - the_internet
    depends_on:
      - sprint-boot-app
      - marshalsec
      - reverse_tcp
      - exploit-http-server

  marshalsec:
    image: marshalsec
    networks:
      - the_internet
    expose:
      - "1389"

  sprint-boot-app:
    image: poc:java8-lookup-disabled
    networks:
      - the_internet
    expose:
      - "8080"
    ports:
      - "8080:8080"

  exploit-http-server:
    image: exploit_nginx
    networks:
      - the_internet
    expose:
      - "80"
    ports:
      - "8888:80"

networks:
  the_internet:
    driver: bridge
    ipam:
     config:
       - subnet: 10.5.0.0/16